version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    labels: ["dependencies", "ci"]
    reviewers: ["DIZ-admin"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "javascript"]
    reviewers: ["DIZ-admin"]

  - package-ecosystem: "gomod"
    directory: "/auth"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "go"]
    reviewers: ["DIZ-admin"]
